Vagrant.configure("2") do |config|
config.vm.box = "bento/debian13"


  config.vm.define "db" do |db|
    db.vm.box = "bento/debian-13"
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provision "shell", path: "provision_db.sh"    
    db.vm.provider "virtualbox" do |vb|
      vb.name = "db-server"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

 config.vm.define "web" do |web|
  web.vm.box = "bento/debian-13"
  web.vm.hostname = "web-server"
  web.vm.network "forwarded_port", guest: 80, host: 8081
  web.vm.network "private_network", ip: "192.168.56.10"
  web.vm.synced_folder "./shared", "/var/www/html"
  web.vm.provision "shell", path: "provision_web.sh"
  web.vm.provider "virtualbox" do |vb|
    vb.name = "web-server"
    vb.memory = 1024
    vb.cpus = 1
  end
 end

end

