


Vagrant.configure("2") do |config|
 


    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.ssh.insert_key = false 
    config.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 1
    end

    config.vm.define :app1 do |app1|
      app1.vm.box = "bento/ubuntu-24.04"
      app1.vm.hostname = "app1"
      app1.vm.network :private_network, ip: "192.168.56.111"
    end

    config.vm.define :app2 do |app2|
      app2.vm.box = "bento/ubuntu-24.04"
      app2.vm.hostname = "app2"
      app2.vm.network :private_network, ip: "192.168.56.112"
    end
  

 
end
