Vagrant.configure("2") do |config|

config.vm.box = "bento/debian-13"
  config.vm.hostname = "lamp-server"
  config.vm.network "forwarded_port", guest: 80, host: 7676
  config.vm.synced_folder "./shared", "/var/www/html",
    owner: "www-data",
    group: "www-data",
    mount_options: ["dmode=755,fmode=644"]

config.vm.provider "virtualbox" do |vb|
  vb.name = "lamp-server"
  vb.memory = 1024
  vb.cpus = 1
end
config.vm.provision "shell", path: "provision.sh"

end


